# Generated by Django 4.2.7 on 2023-11-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(model_name="car", name="title",),
        migrations.AddField(
            model_name="car",
            name="brand",
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="fipeCode",
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="fuel",
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name="car",
            name="model",
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name="car",
            name="price",
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
        ),
        migrations.AddField(
            model_name="car", name="year", field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name="car",
            name="user",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="cars.user",
            ),
        ),
    ]
