# Generated by Django 4.2.7 on 2023-11-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_user_remove_car_title_car_brand_car_fipecode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="name", field=models.TextField(default=""),
        ),
    ]
